version: '3.8'
services:
  bot:
    build:
      context: .
      target: development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./apps/bot:/app
      - /app/node_modules
    command: npm run dev
