name: unit-tests

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Create SQLite database and .env.test
        run: |
          touch tests.db
          echo "BOT_TOKEN=bot-token" > .env.test
          echo "DATABASE_NAME=tests.db" >> .env.test
          echo "NODE_ENV=test" >> .env.test

      - name: Run unit tests
<<<<<<< HEAD
        run: npm run test:github
=======
        run: npm run test
>>>>>>> origin/master
